### PR TITLE
Add caching option for resolving dependencies

### PR DESCRIPTION
**Pull request by karim-alweheshy**
### Checklist

- [x] I've read and followed the [Contribution Guidelines](https://github.com/bitrise-steplib/.github/blob/main/CONTRIBUTING.md)
- [x] `step.yml` and `README.md` is updated with the changes (if needed)

### Version

Requires a *MAJOR/MINOR/PATCH* [version update](https://semver.org/)

### Context
Enable caching of spm dependencies in a custom dir

### CODE REVIEW

**Comment by godrei** [comment]
Hi @KarimAlweheshy,
I wonder what the reason for using a non-default path for SPM dependencies is?

The default path is: `$HOME/Library/Developer/Xcode/DerivedData/[PER_PROJECT_DERIVED_DATA]/SourcePackages` and the relevant iOS Steps are caching this path (based on the `cache_level` Step Input value, which defaults to `swift_packages `).

**Comment by KarimAlweheshy** [comment]
We have our own path to cache as we are not using the default build and archive steps

**Comment by godrei** [comment]
Hi @KarimAlweheshy , could you please elaborate on why you use a custom SPM dependency path, I would like to understand the use case.

I would like to know this to assess this PR and to see if other steps are affected or not.

**Comment by KarimAlweheshy** [comment]
Hey @godrei, it's a preference i would say. There's no must in doing so. But we have our whole dev tools suite built to keep derived data and dependencies all in the same folder along with our code for convenience. There's nothing to assess here imo, there's no new feature, just asking to expose the already existing apis from spm for the ease of use.

**Comment by KarimAlweheshy** [comment]
can we get this moving @godrei ? it's slowing down our ci by a good 10 minutes

**Comment by shams-ahmed** [comment]
Hey,

I spoke to the team about this feature request, and after a few discussions about the context and reasoning for the solution, we decided it best to decline the PR.

We believe it's too focused on a single edge case and we have not seen any other similar request for this specific feature.

However, this step has a few gaps compared to other Xcode related steps so we plan to make improvements that will factor in other customers' requirements (including your one) in the near short term. 

We plan to keep consistent with other steps by adding a `xcodebuild_options` input where you can add your additional flags etc. i.e 
https://github.com/bitrise-steplib/steps-xcode-archive/blob/16729ba49389a2368689f6e6e6b8503cc6d394ed/step.yml#L149

Also, to help with your build times in the short term I would suggest pointing the `manage-ios-code-signing` step to your forked version and branch since this works with the YAML file and workflow editor UI. 

**Yaml:**
from
```
- manage-ios-code-signing@1: {} 
```
to
```
- git::https://github.com/KarimAlweheshy/bitrise-step-manage-ios-code-signing@add-caching-directory-to-resolve-dependencies-in-ci: {} 
```

UI:
Screenshot 2022-05-13 at 4 08 09 pm

**Comment by garry-jeromson** [comment]
+1 on the request for this feature. It's not an edge case, IMO; there are several reasons people may wish to use a non-default location for downloading Swift packages to (in our case: downloading the packages in-band makes them more visible and makes our pipelines less fragile to tooling changes).

**Pull request closed without merging**
